### ISSUE TITLE
Message notifications causing `requested entity was not found` error

### ISSUE THREAD

**Issue by aivantg** [byeokim/gmailpush#10]
I managed to get this set up using the example code you provided almost-exactly, but for some reason, whenever there's a new email, the `getMessages` call consistently errors out with the message `Requested entity was not found.`

If I open the message on the gmail interface (and consequently mark it as read), I get another notification and this one goes through and returns an array of length 1 with the message as expected. 

Any idea why this is happening?

**Comment by aivantg** [comment]
Dug into this a little more. Turns out, the issue was that I was testing my app by sending emails to myself, which triggered the push notification a little too early. I fixed it by: 
- adding a ~3 second delay between receiving a notification and trying to get the message
- _or_ don't email yourself 🤦

**Comment by byeokim** [comment]
Thank you for a use case I didn't know, i.e. sending emails to oneself. I was aware of the case that Gmail API returns 'Not Found' but didn't know it could also return 'Requested entity was not found.'

> For messageDeleted type of history, because messages would have been deleted before requested, return value for those messages would have no material properties and look like this:
>
> ```js
> {
>   id: 'fedcba9876543210',
>   historyType: 'messageDeleted',
>   notFound: true, // Indicates that Gmail API has returned "Not Found" error
>   attachments: [] // Exists only for internal purpose
> }

I [added your case](https://github.com/byeokim/gmailpush/blob/master/lib/gmailpush.js#L251) so now you don't have to instruct your code to wait for ~3 seconds :)
