### ISSUE TITLE
Cannot read property 'readFile'

### ISSUE THREAD

**Issue by enrinal** [byeokim/gmailpush#2]
TypeError: Cannot read property 'readFile' of undefined at Gmailpush._initialize (/srv/node_modules/gmailpush/lib/gmailpush.js:95:18) at Gmailpush.getMessagesWithoutAttachment 

![image](https://user-images.githubusercontent.com/25796956/80794449-2511dd00-8bc4-11ea-860d-006db9bff401.png)

I already initiate gmailpush_history.json

**Comment by enrinal** [comment]
When I change environment to node js 10. This error show up
`SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at Gmailpush._initialize `

**Comment by enrinal** [comment]
This issue can solve if you change environment to node js 10

**Comment by byeokim** [comment]
> TypeError: Cannot read property 'readFile' of undefined at Gmailpush._initialize

The reason that [`fs`](https://github.com/byeokim/gmailpush/blob/master/lib/gmailpush.js#L4) is `undefined` is that [fs Promises API](https://nodejs.org/api/fs.html#fs_fs_promises_api0) was newly added in Node.js v10.0.0. By the way glad that you've solved your problem!
