### ISSUE TITLE
google-map-react-examples/src/examples/MarkerInfoWindow.js

### ISSUE THREAD

**Issue by ingridlar** [byeokim/gmailpush#3]

**Comment by byeokim** [comment]
What were the values of `myPlaces` and `index` at line 137?

`state.myPlaces.findIndex(e => e.id === key)` will return `-1` if there is no element whose `id` property has value equal to `key`. And `state.myPlaces[-1]` will return `undefined`.

By the way as I mentioned you would be better to post this issue on [google-map-react-examples](https://github.com/google-map-react/google-map-react-examples).

**Comment by ingridlar** [comment]
Sorry, I didn’t see your last mail!

Can I invite you to my repository?
If you have the time to help me?

Thank you!



tis 19 maj 2020 kl. 09:55 skrev byeokim <notifications@github.com>:

**Comment by byeokim** [comment]
I cloned your repository and ran the app, but couldn't reproduce your issue.

**Comment by ingridlar** [comment]
Hm.. strange. Did the Infowindow show up when you clicked on a market?

tis 19 maj 2020 kl. 12:44 skrev byeokim <notifications@github.com>:

**Comment by byeokim** [comment]
I had cloned before you commited your lastest code. Now I cloned again. Here is the solution:
1. Add `this.state.` to `myPlaces` at line 193 in `App.js`.

```
// before: {myPlaces.map(place => (
{this.state.myPlaces.map(place => (
```

2. Move `data.json` to `public` directory.
3. For `data.json`, wrap value of `id` with double quotes, e.g. `"id": 1` to `"id": "1"`

**Comment by ingridlar** [comment]
Thanks!!

ons 20 maj 2020 kl. 04:18 skrev byeokim <notifications@github.com>:
